# This file is used to declaratively define the sentry repository labels.
#
# XXX: A note on renaming labels
#
# You MUST use a `alias: [ ... ]` list for the label to specify the old name of
# the label, so that it can correctly rename the label.
#
# Read more here: https://github.com/Financial-Times/github-label-sync#label-config-file

# Unito - www.notion.so/52d10dbfad474328850319e48b057a5b
- name: 'Sync: Jira'
  color: A0CABD
  description: apply to auto-create a Jira shadow ticket

# Dependabot
- name: dependencies
  color: F6F6F8
  description: Pull requests that update a dependency file

# Impacts
- name: 'Impact: Large'
  color: C83852
- name: 'Impact: Medium'
  color: FFB287
- name: 'Impact: Small'
  color: '452650'

# Platforms
- name: 'Platform: .NET'
  color: '584774'
- name: 'Platform: Android'
  color: '584774'
- name: 'Platform: Capacitor'
  color: '584774'
- name: 'Platform: Cocoa'
  color: '584774'
- name: 'Platform: Cordova'
  color: '584774'
- name: 'Platform: Dart'
  color: '584774'
- name: 'Platform: Elixir'
  color: '584774'
- name: 'Platform: Go'
  color: '584774'
- name: 'Platform: Java'
  color: '584774'
- name: 'Platform: JavaScript'
  color: '584774'
- name: 'Platform: KMP'
  color: '584774'
- name: 'Platform: PHP'
  color: '584774'
- name: 'Platform: Python'
  color: '584774'
- name: 'Platform: React-Native'
  color: '584774'
- name: 'Platform: Ruby'
  color: '584774'
- name: 'Platform: Rust'
  color: '584774'
- name: 'Platform: Symfony'
  color: '584774'
- name: 'Platform: Unity'
  color: '584774'
- name: 'Platform: Unreal'
  color: '584774'
- name: 'Platform: Xamarin'
  color: '584774'

# Waiting for Labels
- name: 'Waiting for: Support'
  color: '8D5494'
- name: 'Waiting for: Product Owner'
  color: '8D5494'
- name: 'Waiting for: Community'
  color: '8D5494'
- name: 'Stale'
  color: '8D5494'

# Product Areas - www.notion.so/sentry/473791bae5bf43399d46093050b77bf0
- name: 'Product Area: Unknown'
  color: '8D5494'
- name: 'Product Area: Sign In'
  color: '8D5494'
- name: 'Product Area: Issues'
  color: '8D5494'
- name: 'Product Area: Issues - Source Maps'
  color: '8D5494'
- name: 'Product Area: Issues - Suggested Fix'
  color: '8D5494'
- name: 'Product Area: Projects - Project Creation'
  color: '8D5494'
- name: 'Product Area: Projects - Project Details'
  color: '8D5494'
- name: 'Product Area: Performance'
  color: '8D5494'
- name: 'Product Area: Starfish'
  color: '8D5494'
- name: 'Product Area: Starfish - API'
  color: '8D5494'
- name: 'Product Area: Starfish - Database'
  color: '8D5494'
- name: 'Product Area: Profiling'
  color: '8D5494'
- name: 'Product Area: Replays'
  color: '8D5494'
- name: 'Product Area: Crons'
  color: '8D5494'
- name: 'Product Area: Alerts'
  color: '8D5494'
- name: 'Product Area: Discover'
  color: '8D5494'
- name: 'Product Area: Dashboards'
  color: '8D5494'
- name: 'Product Area: Releases'
  color: '8D5494'
- name: 'Product Area: User Feedback'
  color: '8D5494'
- name: 'Product Area: Stats'
  color: '8D5494'
- name: 'Product Area: Settings'
  color: '8D5494'
- name: 'Product Area: Settings - General'
  color: '8D5494'
- name: 'Product Area: Settings - Projects'
  color: '8D5494'
- name: 'Product Area: Settings - Teams'
  color: '8D5494'
- name: 'Product Area: Settings - Members'
  color: '8D5494'
- name: 'Product Area: Settings - Security & Privacy'
  color: '8D5494'
- name: 'Product Area: Settings - Auth'
  color: '8D5494'
- name: 'Product Area: Settings - Relay'
  color: '8D5494'
- name: 'Product Area: Settings - Repositories'
  color: '8D5494'
- name: 'Product Area: Settings - Integrations'
  color: '8D5494'
- name: 'Product Area: Settings - Developer Settings'
  color: '8D5494'
- name: 'Product Area: Settings - Spend Allocation'
  color: '8D5494'
- name: 'Product Area: Settings - Spike Protection'
  color: '8D5494'
- name: 'Product Area: Settings - Subscription'
  color: '8D5494'
- name: 'Product Area: Help'
  color: '8D5494'
- name: "Product Area: What's New"
  color: '8D5494'
- name: 'Product Area: Footer'
  color: '8D5494'
- name: 'Product Area: SDKs - Web Frontend'
  color: '8D5494'
- name: 'Product Area: SDKs - Web Backend'
  color: '8D5494'
- name: 'Product Area: SDKs - Mobile'
  color: '8D5494'
- name: 'Product Area: SDKs - Native'
  color: '8D5494'
- name: 'Product Area: APIs'
  color: '8D5494'
- name: 'Product Area: Docs'
  color: '8D5494'
- name: 'Product Area: Org Relocation'
  color: '8D5494'
- name: 'Product Area: Other'
  color: '8D5494'

# Teams
- name: 'Team: Crons'
  color: 8D5494
- name: 'Team: Docs'
  color: 8D5494
- name: 'Team: Ecosystem'
  color: 8D5494
- name: 'Team: Emerging Technology'
  color: 8D5494
  description: emerging-technology
- name: 'Team: Enterprise'
  color: 8D5494
- name: 'Team: Front End'
  color: 8D5494
  description: app-frontend
- name: 'Team: Infrastructure'
  color: 8D5494
- name: 'Team: Ingest'
  color: 8D5494
  description: owners-ingest
- name: 'Team: Mobile Platform'
  color: 8D5494
  description: team-mobile
- name: 'Team: Native Platform'
  color: 8D5494
  description: owners-native
- name: 'Team: Open Source'
  color: 8D5494
- name: 'Team: Ops'
  color: 8D5494
- name: 'Team: Replay'
  color: 8D5494
  description: team-replay
- name: 'Team: Revenue'
  color: 8D5494
- name: 'Team: Search & Storage'
  color: 8D5494
  description: sns
- name: 'Team: Telemetry Experience'
  color: 8D5494
  description: telemetry experience team
- name: 'Team: Visibility'
  color: 8D5494
- name: 'Team: Web Frontend'
  color: 8D5494
  description: team-web-sdk-frontend
- name: 'Team: Web SDK Backend'
  color: 8D5494
  description: team-web-sdk-backend
- name: 'Team: Workflow'
  color: 8D5494

# Miscellaneous
- name: API Docs
  color: 649B42
- name: bug
  color: F6F6F8
- name: Common content
  color: B0E299
- name: CSS
  color: 1279F1
- name: duplicate
  color: F6F6F8
- name: 'Effort: Large'
  color: FBCA04
- name: 'Effort: Medium'
  color: FBCA04
- name: 'Effort: Small'
  color: FBCA04
- name: enhancement
  color: F6F6F8
- name: filler
  color: 57D105
  description: Requires little effort to resolve. Ready to be picked up anytime.
- name: filtering and sampling
  color: '584774'
- name: gatsby-bug
  color: e99695
- name: "Hacktoberfest \U0001F383"
  color: ffa500
- name: Hacktoberfest-accepted
  color: e99695
  description: Accept for Hacktoberfest - will merge later
- name: help wanted
  color: F6F6F8
- name: Issues
  color: D6F6D3
- name: javascript
  color: F6F6F8
  description: Pull requests that update Javascript code
- name: Mobile
  color: '584774'
- name: performance
  color: '584774'
- name: up-for-grabs
  color: F6F6F8
- name: wip
  color: F6F6F8
- name: wontfix
  color: F6F6F8
- name: Product Docs
  color: F31984
- name: projects
  color: F6F6F8
- name: question
  color: F6F6F8
- name: release health
  color: F6F6F8
