# This file is used to declaratively define the sentry repository labels.
#
# XXX: A note on renaming labels
#
# You MUST use a `alias: [ ... ]` list for the label to specify the old name of
# the label, so that it can correctly rename the label.
#
# Read more here: https://github.com/Financial-Times/github-label-sync#label-config-file

# Unito - notion.so/52d10dbfad474328850319e48b057a5b
- name: 'Sync: Jira'
  aliases: []
  color: A0CABD
  description: apply to auto-create a Jira shadow ticket

# Dependabot
- name: dependencies
  aliases: []
  color: F6F6F8
  description: Pull requests that update a dependency file

# Status for use with stalebot and routing/triage
- name: 'Status: As Designed'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Status: Backlog'
  aliases: []
  color: 8D5494
  description: stalebot will ignore
- name: 'Status: Done'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Status: In Progress'
  aliases: []
  color: 8D5494
  description: stalebot will ignore
- name: 'Status: Invalid'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Status: Needs More Information'
  aliases: []
  color: 8D5494
  description: stalebot will close after four weeks of inactivity
- name: 'Status: Stale'
  aliases: []
  color: 8D5494
  description: stalebot will close after another week of inactivity
- name: 'Status: Unrouted'
  aliases: []
  color: 8D5494
  description: stalebot will close after four weeks of inactivity
- name: 'Status: Untriaged'
  aliases: []
  color: 8D5494
  description: stalebot will close after four weeks of inactivity
- name: 'Status: Won''t Fix'
  aliases: []
  color: 8D5494
  description: ''

# Impacts
- name: 'Impact: Large'
  aliases: []
  color: C83852
  description: ''
- name: 'Impact: Medium'
  aliases: []
  color: FFB287
  description: ''
- name: 'Impact: Small'
  aliases: []
  color: '452650'
  description: ''

# Platforms
- name: 'Platform: .NET'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Android'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Capacitor'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Cocoa'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Cordova'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Dart'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Elixir'
  aliases: []
  color: 3268A0
  description: ''
- name: 'Platform: Go'
  aliases: []
  color: 2A5DD0
  description: ''
- name: 'Platform: Java'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: JavaScript'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: PHP'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Python'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: React-Native'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Ruby'
  aliases: []
  color: '584774'
  description: Pull requests that update Ruby code
- name: 'Platform: Rust'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Symfony'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Unity'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Unreal'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Xamarin'
  aliases: []
  color: '584774'
  description: ''

# Teams
- name: 'Team: Crons'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Docs'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Ecosystem'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Emerging Technology'
  aliases: []
  color: 8D5494
  description: emerging-technology
- name: 'Team: Enterprise'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Front End'
  aliases: []
  color: 8D5494
  description: app-frontend
- name: 'Team: Infrastructure'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Ingest'
  aliases: []
  color: 8D5494
  description: owners-ingest
- name: 'Team: Mobile Platform'
  aliases: []
  color: 8D5494
  description: team-mobile
- name: 'Team: Native Platform'
  aliases: []
  color: 8D5494
  description: owners-native
- name: 'Team: Open Source'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Ops'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Replay'
  aliases: []
  color: 8D5494
  description: team-replay
- name: 'Team: Revenue'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Search & Storage'
  aliases: []
  color: 8D5494
  description: sns
- name: 'Team: Telemetry Experience'
  aliases: []
  color: 8D5494
  description: telemetry experience team
- name: 'Team: Visibility'
  aliases: []
  color: 8D5494
  description: ''
- name: 'Team: Web Frontend'
  aliases: []
  color: 8D5494
  description: team-web-sdk-frontend
- name: 'Team: Web SDK Backend'
  aliases: []
  color: 8D5494
  description: team-web-sdk-backend
- name: 'Team: Workflow'
  aliases: []
  color: 8D5494
  description: ''

# Miscellaneous
- name: API Docs
  aliases: []
  color: 649B42
  description: ''
- name: bug
  aliases: []
  color: F6F6F8
  description: ''
- name: Common content
  aliases: []
  color: B0E299
  description: ''
- name: CSS
  aliases: []
  color: 1279F1
  description: ''
- name: duplicate
  aliases: []
  color: F6F6F8
  description: ''
- name: 'Effort: Large'
  aliases: []
  color: FBCA04
  description: ''
- name: 'Effort: Medium'
  aliases: []
  color: FBCA04
  description: ''
- name: 'Effort: Small'
  aliases: []
  color: FBCA04
  description: ''
- name: enhancement
  aliases: []
  color: F6F6F8
  description: ''
- name: filler
  aliases: []
  color: 57D105
  description: Requires little effort to resolve. Ready to be picked up anytime.
- name: filtering and sampling
  aliases: []
  color: '584774'
  description: ''
- name: gatsby-bug
  aliases: []
  color: e99695
  description: ''
- name: "Hacktoberfest \U0001F383"
  aliases: []
  color: ffa500
  description: ''
- name: Hacktoberfest-accepted
  aliases: []
  color: e99695
  description: Accept for Hacktoberfest - will merge later
- name: help wanted
  aliases: []
  color: F6F6F8
  description: ''
- name: Issues
  aliases: []
  color: D6F6D3
  description: ''
- name: javascript
  aliases: []
  color: F6F6F8
  description: Pull requests that update Javascript code
- name: Mobile
  aliases: []
  color: '584774'
  description: ''
- name: performance
  aliases: []
  color: '584774'
  description: ''
- name: up-for-grabs
  aliases: []
  color: F6F6F8
  description: ''
- name: wip
  aliases: []
  color: F6F6F8
  description: ''
- name: wontfix
  aliases: []
  color: F6F6F8
  description: ''
- name: Product Docs
  aliases: []
  color: F31984
  description: ''
- name: projects
  aliases: []
  color: F6F6F8
  description: ''
- name: question
  aliases: []
  color: F6F6F8
  description: ''
- name: release health
  aliases: []
  color: F6F6F8
  description: ''
