# This file is used to declaratively define the sentry repository labels.
#
# XXX: A note on renaming labels
#
# You MUST use a `alias: [ ... ]` list for the label to specify the old name of
# the label, so that it can correctly rename the label.
#
# Read more here: https://github.com/Financial-Times/github-label-sync#label-config-file

- name: API Docs
  aliases: []
  color: 649B42
  description: ''
- name: bug
  aliases: []
  color: F6F6F8
  description: ''
- name: Common content
  aliases: []
  color: B0E299
  description: ''
- name: CSS
  aliases: []
  color: 1279F1
  description: ''
- name: dependencies
  aliases: []
  color: F6F6F8
  description: Pull requests that update a dependency file
- name: duplicate
  aliases: []
  color: F6F6F8
  description: ''
- name: 'Effort: Large'
  aliases: []
  color: FBCA04
  description: ''
- name: 'Effort: Medium'
  aliases: []
  color: FBCA04
  description: ''
- name: 'Effort: Small'
  aliases: []
  color: FBCA04
  description: ''
- name: enhancement
  aliases: []
  color: F6F6F8
  description: ''
- name: filler
  aliases: []
  color: 57D105
  description: Requires little effort to resolve. Ready to be picked up anytime.
- name: filtering and sampling
  aliases: []
  color: '584774'
  description: ''
- name: gatsby-bug
  aliases: []
  color: e99695
  description: ''
- name: "Hacktoberfest \U0001F383"
  aliases: []
  color: ffa500
  description: ''
- name: Hacktoberfest-accepted
  aliases: []
  color: e99695
  description: Accept for Hacktoberfest - will merge later
- name: help wanted
  aliases: []
  color: F6F6F8
  description: ''
- name: 'Impact: Large'
  aliases: []
  color: C83852
  description: ''
- name: 'Impact: Medium'
  aliases: []
  color: FFB287
  description: ''
- name: 'Impact: Small'
  aliases: []
  color: '452650'
  description: ''
- name: Issues
  aliases: []
  color: D6F6D3
  description: ''
- name: javascript
  aliases: []
  color: F6F6F8
  description: Pull requests that update Javascript code
- name: Mobile
  aliases: []
  color: '584774'
  description: ''
- name: performance
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: .NET'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Android'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Capacitor'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Cocoa'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Cordova'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Dart'
  aliases: []
  color: '584774'
  description: ''
- name: 'Platform: Elixir'
  aliases: []
  color: 3268A0
  description: ''
