sudo: false
language: ruby
rvm:
  - 2.5.1
node_js:
  - 'node'
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
script:
  - yarn test-jekyll
  - yarn run snyk-protect
dist: trusty
