sudo: false
language: ruby
rvm:
  - 2.5.1
node_js:
  - 'node'
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
script:
  - bin/test
  - yarn run snyk-protect
dist: trusty
