steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/$REPO_NAME:build || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/$REPO_NAME:latest || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--target', 'build',
    '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:build',
    '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
    '--build-arg', 'BRANCH_NAME=$BRANCH_NAME',
    '--build-arg', 'BUILD_CONF=${_BUILD_CONF}',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:build',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
    '--build-arg', 'BRANCH_NAME=$BRANCH_NAME',
    '--build-arg', 'BUILD_CONF=${_BUILD_CONF}',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:build',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
]
images: [
  'us.gcr.io/$PROJECT_ID/$REPO_NAME:build',
  'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
  'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
]
timeout: 3000s
logsBucket: 'gs://sentryio-cloudbuild-logs/sentry-docs'
