.. class:: platformlink row

*   .. class:: platformlink-python

    :doc:`/clients/python/index` Including Django, Flask, and others.

*   .. class:: platformlink-js

    :doc:`/clients/javascript/index` Including Node, Browser environments etc.

*   .. class:: platformlink-php

    :doc:`/clients/php/index` Including PHP apps.

*   .. class:: platformlink-ruby

    :doc:`/clients/ruby/index` Including Rails, Sinatra, Rack and others.

*   .. class:: platformlink-objc

    :doc:`/clients/objc/index` For iOS and Mac.

*   .. class:: platformlink-java

    :doc:`/clients/java/index` For Java and Android.

*   .. class:: platformlink-csharp

    :doc:`/clients/csharp/index` Including Mono and .NET languages.
