.. class:: platformlink row

*   .. class:: platformlink-python

    :doc:`/clients/python/index` Including Django, Flask, Pyramid, and others.

*   .. class:: platformlink-js

    :doc:`/clients/javascript/index` Including React, Angular, Ember, Vue, and Backbone.

*   .. class:: platformlink-node

    :doc:`/clients/node/index` Including Express, Koa, and Connect.

*   .. class:: platformlink-php

    :doc:`/clients/php/index` Including Laravel, Symfony, and Monolog.

*   .. class:: platformlink-ruby

    :doc:`/clients/ruby/index` Including Rails, Sinatra, Rack, and others.

*   .. class:: platformlink-objc

    :doc:`/clients/cocoa/index` For iOS, macOS, and tvOS.

*   .. class:: platformlink-java

    :doc:`/clients/java/index` For Java and Android.

*   .. class:: platformlink-csharp

    :doc:`/clients/csharp/index` Including Mono and .NET languages.

*   .. class:: platformlink-go

    :doc:`/clients/go/index` For Google's Go Language

*   .. class:: platformlink-perl

    :doc:`/clients/perl/index` For Perl apps.

*   .. class:: platformlink-actionscript

    :doc:`/clients/actionscript/index` For ActionScript 3.
