.. class:: platformlink

*   .. class:: platformlink-python

    :doc:`/clients/python/index` — including Django, Flask etc.

*   .. class:: platformlink-js

    :doc:`/clients/javascript/index` — including Node, Browser environments etc.

*   .. class:: platformlink-php

    :doc:`/clients/php/index` — including PHP applications

*   .. class:: platformlink-ruby

    :doc:`/clients/ruby/index` — including Rails, Sinatra, Rack and other environments.

*   .. class:: platformlink-objc

    :doc:`/clients/objc/index` — for iOS and Mac.

*   .. class:: platformlink-java

    :doc:`/clients/java/index` — for Java and Android.

*   .. class:: platformlink-csharp

    :doc:`/clients/csharp/index` — including Mono and .NET languages.
