title: React
caseStyle: camelCase
supportLevel: production
sdk: sentry.javascript.react
fallbackPlatform: javascript
categories:
  - browser
redirect_from:
  - /platforms/javascript/react/
  - /clients/javascript/integrations/react/
  - /sdks/react/
  - /platforms/react/
description: "Learn about Sentry's React SDK and how it automatically reports errors and exceptions in your application."
