title: Vue
caseStyle: camelCase
supportLevel: production
sdk: sentry.javascript.vue
fallbackPlatform: javascript
categories:
  - browser
redirect_from:
  - /platforms/javascript/vue/
  - /clients/javascript/integrations/vue/
