title: AWS Lambda
description: AWS Lambda is a serverless compute service offered as part of Amazon Web Services. Learn how to set it up with Sentry.
sdk: sentry.javascript.aws-serverless
categories:
  - javascript
  - server
  - server-node
  - serverless
