title: TanStack Start React
description: Learn how to set up TanStack Start React with Sentry.
sdk: sentry.javascript.tanstackstart-react
categories:
  - javascript
  - server
  - server-node
  - browser
