title: TanStack Start React
description: Learn how to set up and configure Sentry in your TanStack Start React application, capturing your first errors, and viewing them in Sentry.
sdk: sentry.javascript.tanstackstart-react
categories:
  - javascript
  - server
  - server-node
  - browser
