title: SolidStart
description: SolidStart is a framework for full-stack web apps and websites. Learn how to set it up with Sentry.
sdk: sentry.javascript.solidstart
categories:
  - browser
  - server
