name: "📝 Documentation on develop.sentry.dev"
labels: ["Type: Content", "Develop"]
description: Missing, incorrect, or unclear developer documentation.
body:
  - type: markdown
    attributes:
      value: |-
        Is the documentation issue something you know how to fix? Consider contributing to Open Source by opening a PR to fix it instead!
  - type: input
    id: area-specific
    attributes:
      label: Which section?
      description: Which section of the developer documentation needs to be updated?
    validations:
      required: true
  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Please provide the URL of the page which should be changed (if applicable).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What were you looking for/trying to do/expecting?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: If you have an idea on how we can solve this, please share.
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.
  
