name: New doc
description: Create a new markdown doc from a template
title: "New doc: "
labels: ["doc-request"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: The page title shown at the top of the doc
      placeholder: "My new doc"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: Slug
      description: Used as the filename. Lowercase, hyphens. Example: my-new-doc
      placeholder: "my-new-doc"
    validations:
      required: true

  - type: dropdown
    id: folder
    attributes:
      label: Folder
      description: Where to place the doc
      options:
        - docs/product
        - docs/platform
        - docs/guides
    validations:
      required: true

  - type: input
    id: owner
    attributes:
      label: Owner / team
      placeholder: "team-foo"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: 1–3 sentences to include near the top
      placeholder: "This doc explains..."
    validations:
      required: true

  - type: textarea
    id: extra_sections
    attributes:
      label: Extra sections (optional)
      description: Add section headings you want included (one per line)
      placeholder: |
        FAQ
        Troubleshooting
    validations:
      required: false
