name: 🐞 Documentation Issue
description: Missing, incorrect, unclear documentation or code samples.
body:
  - type: dropdown
    id: area
    attributes:
      label: Core or SDK?
      description: What part of the Sentry documentation are we talking about?
      options:
        - Core Sentry product
        - Platform/SDK
    validations:
      required: true
  - type: input
    id: area-specific
    attributes:
      label: Which part? Which one?
      description: Which area of the core Sentry product, or which platform/SDK?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What were you looking for/trying to do/expecting?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: If you have an idea on how we can solve this, please share.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.
    validations:
      required: false

