name: "📝 Product Documentation"
labels: ["Type: Content", "Product"]
description: Missing, incorrect, or unclear documentation of product features.
body:
  - type: markdown
    attributes:
      value: |-
        Is the documentation issue something you know how to fix? Consider contributing to Open Source by opening a PR to fix it instead!
  - type: input
    id: area-specific
    attributes:
      label: Which part? Which one?
      description: Which area of the core Sentry product?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What were you looking for/trying to do/expecting?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: If you have an idea on how we can solve this, please share.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.
