name: "📝 SDK Documentation"
labels: ["Type: Content", "SDKs"]
description: Missing, incorrect, or unclear documentation of SDKs.
body:
  - type: markdown
    attributes:
      value: |-
        Is the documentation issue something you know how to fix? Consider contributing to Open Source by opening a PR to fix it instead!
  - type: dropdown
    id: area
    attributes:
      label: SDK
      description: Which SDK documentation are we talking about?
      options:
        - Android SDK
        - Apple SDK
        - Dart SDK
        - Elixir SDK
        - Flutter SDK
        - Go SDK
        - Java SDK
        - JavaScript SDK
        - Kotlin Multiplatform SDK
        - Native SDK
        - .NET SDK
        - PHP SDK
        - PowerShell SDK
        - Python SDK
        - React Native SDK
        - Ruby SDK
        - Rust SDK
        - Unity SDK
        - Unreal Engine SDK
        - Sentry CLI
        - All JavaScript SDKs
        - All Backend SDKs
        - All Mobile SDKs
        - All Gaming SDKs
        - All SDKs
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What were you looking for/trying to do/expecting?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: If you have an idea on how we can solve this, please share.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.
