name: New Integration Doc (Organization > Integrations)
description: Generate an integration doc page under docs/organization/integrations/<category>/<slug>/index.mdx
title: "Integration docs: "
labels: ["doc-request", "docs", "integrations"]
body:
  - type: markdown
    attributes:
      value: |
        This creates a PR that:
        1) adds `docs/organization/integrations/<category>/<slug>/index.mdx`
        2) (optionally) updates the category `docs/organization/integrations/<category>/index.mdx` to link to it.

  - type: input
    id: integration_title
    attributes:
      label: Integration name (title)
      description: Used for the page `title:` frontmatter.
      placeholder: "Unleash"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: Slug (folder name)
      description: Lowercase with hyphens. Will create `.../<slug>/index.mdx`.
      placeholder: "unleash"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Integration category (folder under docs/organization/integrations)
      description: Picks the section where the doc will live.
      options:
        - feature-flag
        - source-code-mgmt
        - issue-tracking
        - deployment
        - notification-incidents
        - cloud-monitoring
        - data-forwarding
        - compliance
        - debugging
        - session-replay
        - other
    validations:
      required: true

  - type: input
    id: sidebar_order
    attributes:
      label: Sidebar order
      description: Numeric ordering in the left nav for this category (example pages use `sidebar_order`).
      placeholder: "2"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Short description (frontmatter)
      description: Used for `description:` frontmatter. Keep it short; sentence case.
      placeholder: "Learn about Sentry's <Integration> integration."
    validations:
      required: true

  - type: checkboxes
    id: update_category_index
    attributes:
      label: Update category index page
      description: Add a link entry to `docs/organization/integrations/<category>/index.mdx` (common pattern).
      options:
        - label: "Yes — add link to the category index.mdx"
          required: false

  - type: textarea
    id: overview
    attributes:
      label: Overview (what this integration does)
      description: 1–3 paragraphs. What problems it solves / what you get.
      placeholder: |
        Sentry's <Integration> integration lets you...
    validations:
      required: true

  - type: checkboxes
    id: capabilities
    attributes:
      label: Integration capabilities
      description: Select what applies; the doc can generate sections accordingly.
      options:
        - label: Install / connect from Sentry UI
        - label: Alerts / notifications
        - label: Issue creation / issue sync
        - label: Code linking / commit association
        - label: Deploy tracking
        - label: Feature flag evaluation tracking
        - label: Webhook-based change tracking
        - label: SSO / SCIM provisioning
        - label: Data forwarding / ingestion
        - label: Other (describe below)

  - type: textarea
    id: setup
    attributes:
      label: Setup steps
      description: Step-by-step instructions. If there are multiple flows, separate with headings.
      placeholder: |
        1. In Sentry, go to Settings → Integrations → ...
        2. Click ...
        3. In <Integration>, create ...
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration details (optional)
      description: Scopes/permissions, required settings, webhook secret requirements, etc.
      placeholder: |
        Required permissions:
        - ...
        Webhook events:
        - ...
    validations:
      required: false

  - type: textarea
    id: supported_platforms
    attributes:
      label: Links to supported platforms / SDK docs (optional)
      description: If setup differs by language/platform, include links (one per line).
      placeholder: |
        - /platforms/javascript/...
        - /platforms/python/...
    validations:
      required: false

  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting (optional)
      description: Common pitfalls, error messages, how to verify it’s working.
      placeholder: |
        - If you see ...
          - Check ...
    validations:
      required: false

  - type: textarea
    id: uninstall
    attributes:
      label: Uninstall / disconnect (optional)
      placeholder: |
        To remove the integration...
    validations:
      required: false

  - type: textarea
    id: assets
    attributes:
      label: Images / screenshots to include (optional)
      description: Note filenames/paths you will add (or want the PR to create placeholders for).
      placeholder: |
        - ./img/screenshot-1.png (shows ...)
    validations:
      required: false

  - type: input
    id: owner
    attributes:
      label: Doc owner / reviewer
      description: Team or handle to request review from (used for PR body or CODEOWNERS hint).
      placeholder: "@team-web-frontend"
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: Links to product spec, integration docs, Jira ticket, etc.
      placeholder: |
        - https://...
    validations:
      required: false
