name: New Integration Doc (Organization > Integrations)
description: Generate an integration doc page under docs/organization/integrations/<category>/<slug>.md
title: "Integration docs: "
labels: ["doc-request", "docs", "integrations"]
body:
  - type: markdown
    attributes:
      value: |
        This request generates a docs page for an integration under:
        docs/organization/integrations/<category>/<slug>.md

        It will include:
        - A lead "Learn about Sentry's <title> integration ..." description
        - An "Install and Configure" section (required)

  - type: input
    id: title
    attributes:
      label: Integration name
      placeholder: "Blar"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: Slug (filename)
      description: Lowercase, hyphens. This becomes <slug>.md
      placeholder: "blar"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Integration category (folder)
      description: Folder under docs/organization/integrations/
      options:
        - notification-incidents
        - source-code-mgmt
        - issue-tracking
        - deployment
        - debugging
        - compliance
        - data-forwarding
        - cloud-monitoring
        - session-replay
        - other
    validations:
      required: true

  - type: textarea
    id: learn_about_sentence
    attributes:
      label: "Lead sentence (Learn about...)"
      description: This becomes the first sentence on the page.
      placeholder: "Learn about Sentry's <Integration> integration and how it ..."
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview (1–2 short paragraphs)
      description: What it does + what value users get.
      placeholder: |
        <Integration> captures...
        This helps developers...
    validations:
      required: true

  - type: checkboxes
    id: ownership
    attributes:
      label: Maintained & supported by
      description: Many pages include a line stating who maintains it.
      options:
        - label: "Third-party (company that created it)"
        - label: "Sentry"
        - label: "Other (specify below)"
    validations:
      required: true

  - type: input
    id: maintained_by
    attributes:
      label: Maintained by (name)
      description: If not Sentry, include company/project name.
      placeholder: "Acme, Inc."
    validations:
      required: false

  - type: input
    id: support_contact
    attributes:
      label: Support contact (optional)
      description: Email or URL if the page should include a support contact line.
      placeholder: "support@example.com"
    validations:
      required: false

  - type: input
    id: permissions_required
    attributes:
      label: Permissions required (Sentry)
      description: Example: "Sentry Owner, Manager, or Admin permissions are required..."
      placeholder: "Sentry Owner, Manager, or Admin permissions are required to install this integration."
    validations:
      required: true

  - type: textarea
    id: install_and_configure_steps
    attributes:
      label: Install and Configure (required steps)
      description: Use numbered steps. Include the exact Settings path(s) and any external install link.
      placeholder: |
        1. In Sentry, navigate to Settings > Integrations > <Integration>.
        2. Click Install.
        3. In the modal, ...
        4. Follow the full <Integration> installation instructions: https://...
    validations:
      required: true

  - type: textarea
    id: configure_details
    attributes:
      label: Configuration details (optional)
      description: Scopes/permissions on the third-party side, webhook details, required settings, etc.
      placeholder: |
        Required permissions:
        - ...
        Webhook events:
        - ...
    validations:
      required: false

  - type: textarea
    id: verify_it_works
    attributes:
      label: Verify it works (optional)
      description: How a user confirms the integration is correctly installed.
      placeholder: |
        - Trigger an alert and confirm...
        - Confirm events appear in...
    validations:
      required: false

  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting (optional)
      description: Common issues and fixes.
      placeholder: |
        - If you see ...
          - Check ...
    validations:
      required: false

  - type: checkboxes
    id: include_platform_link
    attributes:
      label: Include Integration Platform link line
      description: Many pages mention "For more details, check out our Integration Platform documentation."
      options:
        - label: "Yes — add Integration Platform link line"
    validations:
      required: false

  - type: input
    id: pr_reviewer
    attributes:
      label: Suggested reviewer / owner
      placeholder: "@getsentry/team-web-frontend"
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: Product spec, integration listing, ticket, etc.
      placeholder: |
        - https://sentry.io/integrations/<slug>/
        - https://...
    validations:
      required: false
