title: React Router v7 (framework mode)
description: React Router v7 is a framework for building full-stack web apps and websites. Learn how to set it up with Sentry.
sdk: sentry.javascript.react-router
categories:
  - javascript
  - browser
  - server
  - server-node
