#!/usr/bin/env ts-node

/**
 * Map Template Generator
 *
 * Reads the inventory manifest and generates a template screenshot-map.yaml
 * with empty URL fields for each stale standard screenshot. This makes it
 * easier to manually fill in the URL mappings.
 *
 * Usage:
 *   npx ts-node scripts/screenshot-pipeline/tools/generate-map-template.ts
 *   npx ts-node scripts/screenshot-pipeline/tools/generate-map-template.ts --scope docs/product/insights
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import {AssetInventoryItem} from '../src/lib/types';

function main() {
  const repoRoot = findRepoRoot();
  const scope = getCliArg('--scope');

  // Load inventory manifest
  const manifestPath = path.join(
    repoRoot,
    'scripts/screenshot-pipeline/output/inventory-manifest.json'
  );

  if (!fs.existsSync(manifestPath)) {
    console.error(`Error: Inventory manifest not found at ${manifestPath}`);
    console.error('Run the inventory crawler first: npm run crawl');
    process.exit(1);
  }

  const inventory: AssetInventoryItem[] = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));

  // Filter to stale standard screenshots
  let screenshots = inventory.filter(
    item => item.asset_type === 'standard_screenshot' && item.is_stale
  );

  // Apply scope filter
  if (scope) {
    screenshots = screenshots.filter(
      item => item.asset_path.startsWith(scope) || item.doc_path.startsWith(scope)
    );
  }

  // Deduplicate by asset_path
  const uniqueAssets = new Map<string, AssetInventoryItem>();
  for (const item of screenshots) {
    if (!uniqueAssets.has(item.asset_path)) {
      uniqueAssets.set(item.asset_path, item);
    }
  }

  // Group by doc section for readability
  const bySection = new Map<string, AssetInventoryItem[]>();
  for (const item of uniqueAssets.values()) {
    const parts = item.doc_path.split('/');
    const section = parts.slice(0, 3).join('/'); // e.g., "docs/product/insights"
    if (!bySection.has(section)) {
      bySection.set(section, []);
    }
    bySection.get(section)!.push(item);
  }

  // Generate YAML template
  const lines: string[] = [
    '# Screenshot URL Mapping',
    '#',
    '# Generated by: npx ts-node scripts/screenshot-pipeline/tools/generate-map-template.ts',
    `# Generated at: ${new Date().toISOString()}`,
    `# Total entries: ${uniqueAssets.size}`,
    '#',
    '# Fill in ui_page_url for each entry with the Sentry UI page that matches this screenshot.',
    '# Use {org} as a placeholder for the org slug.',
    '#',
    '# After filling in URLs, copy entries to config/screenshot-map.yaml',
    '',
  ];

  for (const [section, items] of [...bySection.entries()].sort()) {
    lines.push(`# --- ${section} ---`);
    lines.push('');

    for (const item of items.sort((a, b) => a.asset_path.localeCompare(b.asset_path))) {
      lines.push(`- asset_path: ${item.asset_path}`);
      lines.push(`  ui_page_url: "" # TODO: Fill in Sentry UI URL`);
      lines.push(`  element_selector: null`);
      lines.push(`  viewport: { width: 1280, height: 800 }`);
      lines.push(`  auth_required: true`);
      lines.push(`  deterministic: true`);
      lines.push(`  wait_for: null`);
      lines.push(`  ignore_regions: []`);
      lines.push(
        `  # doc: ${item.doc_path}` +
          (item.alt_text ? ` | alt: "${item.alt_text}"` : '')
      );
      lines.push('');
    }
  }

  // Write template
  const outputDir = path.join(repoRoot, 'scripts/screenshot-pipeline/output');
  fs.mkdirSync(outputDir, {recursive: true});
  const outputPath = path.join(outputDir, 'screenshot-map-template.yaml');
  fs.writeFileSync(outputPath, lines.join('\n'));

  console.log(`Generated map template with ${uniqueAssets.size} entries`);
  console.log(`Sections: ${bySection.size}`);
  console.log(`Written to: ${outputPath}`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. Open the template and fill in ui_page_url for each entry');
  console.log('  2. Copy completed entries to config/screenshot-map.yaml');
}

// ── Helpers ──

function findRepoRoot(): string {
  let dir = __dirname;
  for (let i = 0; i < 10; i++) {
    const pkgPath = path.join(dir, 'package.json');
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
        if (pkg.name === 'sentry-docs') {
          return dir;
        }
      } catch {
        // continue
      }
    }
    dir = path.dirname(dir);
  }
  return process.cwd();
}

function getCliArg(flag: string): string | null {
  const idx = process.argv.indexOf(flag);
  if (idx >= 0 && idx + 1 < process.argv.length) {
    return process.argv[idx + 1];
  }
  return null;
}

// ── Entry Point ──

main();
