# Enforce Title Case for headings
extends: capitalization
message: "Use Title Case for headings: '%s'"
level: suggestion
scope: heading
match: $title
style: AP
# Allow certain words to be lowercase in titles
indicators:
  - ":"
exceptions:
  - a
  - an
  - and
  - as
  - at
  - but
  - by
  - for
  - in
  - nor
  - of
  - on
  - or
  - so
  - the
  - to
  - up
  - yet
  - vs
  - via
