# Sentry inclusive language rules
# See: https://develop.sentry.dev/getting-started/inclusive-language/
extends: substitution
message: "Use '%s' instead of '%s' for inclusive language."
level: warning
ignorecase: true
swap:
  blacklist: blocklist
  whitelist: allowlist
  blacklisted: blocked
  whitelisted: allowed
  master/slave: primary/replica
  grandfathered: legacy
