# Avoid corporate marketing language
extends: existence
message: "Avoid marketing speak: '%s'. Be direct and specific instead."
level: suggestion
ignorecase: true
tokens:
  - best-in-class
  - best in class
  - world-class
  - world class
  - cutting-edge
  - cutting edge
  - industry-leading
  - industry leading
  - leverage
  - leveraging
  - leverages
  - synergy
  - synergies
  - synergize
  - paradigm
  - paradigm shift
  - game-changer
  - game changer
  - revolutionary
  - revolutionize
  - disruptive
  - next-generation
  - next generation
  - bleeding-edge
  - bleeding edge
  - robust solution
  - seamlessly
  - empower
  - empowers
  - empowering
