# Ensure proper capitalization of Sentry product names
extends: substitution
message: "Use '%s' instead of '%s' for proper capitalization."
level: warning
ignorecase: false
swap:
  '(?<![A-Za-z])sentry(?![A-Za-z-])': Sentry
  'Sentry sdk': Sentry SDK
  'sentry SDK': Sentry SDK
  'sentry sdk': Sentry SDK
  '(?<![A-Za-z])dsn(?![A-Za-z])': DSN
  javascript: JavaScript
  Javascript: JavaScript
  typescript: TypeScript
  Typescript: TypeScript
