# Flag overly long sentences
extends: occurrence
message: "This sentence has %s words. Consider breaking it into shorter sentences (aim for under 25 words)."
level: suggestion
# Count words in a sentence
scope: sentence
max: 35
token: '\b\w+\b'
