# Prefer simpler words and phrases
extends: substitution
message: "Consider using '%s' instead of '%s' for clarity."
level: suggestion
ignorecase: true
swap:
  in order to: to
  utilize: use
  utilizes: uses
  utilizing: using
  prior to: before
  subsequent to: after
  in the event that: if
  at this point in time: now
  due to the fact that: because
  for the purpose of: to
  in close proximity to: near
  a large number of: many
  the majority of: most
  in spite of the fact that: although
  click on: click
