title: React
description: "Learn about Sentry's React SDK and how it automatically reports errors and exceptions in your application."
sdk: sentry.javascript.react
categories:
  - javascript
  - browser
