title: Azure Functions
description: Azure Functions is a serverless compute service offered as part of Microsoft Azure. Learn how to set it up with Sentry.
sdk: sentry.javascript.astro
categories:
  - javascript
  - server
  - server-node
  - serverless
