title: Effect
description: Learn how to set up and configure Sentry in your Effect application, capture your first errors, and view them in Sentry.
sdk: sentry.javascript.effect
categories:
  - javascript
  - server
  - server-node
  - browser
