#!/usr/bin/env bash
echo "--> Starting postgres"
su postgres -c 'mkdir -p /var/lib/postgresql/data'
su postgres -c '/usr/lib/postgresql/9.6/bin/initdb -D /var/lib/postgresql/data'
su postgres -c '/usr/lib/postgresql/9.6/bin/pg_ctl -D /var/lib/postgresql/data start' &
su postgres -c 'createdb -U postgres -E utf8 --template template0 sentry_api_docs'
su postgres -c 'psql -U postgres -h 127.0.0.1 -c "CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;"'

echo "--> Fetching sentry source"
curl -Ls https://github.com/getsentry/sentry/archive/master.zip --output sentry.zip
unzip sentry.zip

echo "--> Installing sentry dependencies"
cd sentry-master

export SENTRY_LIGHT_BUILD=1
pip install -U setuptools
pip install -e '.[dev]'

echo "--> Starting Redis"
redis-server &

echo "--> Building API docs"
python api-docs/generator.py --output-path=/usr/src/output --output-format=both
