#!/usr/bin/env bash
branch="meredith/test-fixing-apidoc-generator"
cd_branch="sentry-meredith-test-fixing-apidoc-generator"

echo "--> Starting docker daemon"
dockerd &

echo "--> Fetching sentry source"
curl -Ls https://github.com/getsentry/sentry/archive/${branch}.zip --output sentry.zip
unzip sentry.zip

echo "--> Installing sentry dependencies"
cd ${cd_branch}

export SENTRY_LIGHT_BUILD=1
pip install -U setuptools
pip install -e '.[dev]'

echo "--> Building API docs"
python api-docs/generator.py --output-path=/usr/src/output --output-format=both
