title: Go
description: Sentry's Go SDK supports all recent versions of the language, and integrates well with a variety of popular frameworks and packages in the Go ecosystem. It gives developers helpful hints for where and why an error or panic might have occurred.
sdk: sentry.go
supportLevel: production
caseStyle: PascalCase
