import {NavItemsProps} from './types/changelog';

export const NAV_ITEMS: NavItemsProps[] = [
  {
    id: 'product',
    title: 'Product',
    type: 'button',
    variant: 'ghost',
    className: '',
    children: [
      {
        id: 'platform',
        title: 'Platform',
        children: [
          {
            id: 'errorMonitoring',
            title: 'Error Monitoring',
            to: 'https://sentry.io/for/error-monitoring/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'sessionReplay',
            title: 'Session Replay',
            to: 'https://sentry.engineering/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'performance',
            title: 'Performance',
            to: 'https://sentry.io/for/performance/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'profiling',
            title: 'Profiling',
            to: 'https://sentry.io/for/profiling/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'cronMonitoring',
            title: 'Cron Monitoring',
            to: 'https://sentry.io/for/cron-monitoring/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'codeCoverage',
            title: 'Code Coverage',
            to: 'https://sentry.io/for/code-coverage/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'integrations',
            title: 'Integrations',
            to: 'https://sentry.io/integrations/',
            variant: 'ghost',
            type: 'a',
          },
        ],
      },
      {
        id: 'languages&Frameworks',
        title: 'Languages & Frameworks',
        children: [
          {
            id: 'javascript',
            title: 'Javascript',
            to: 'https://sentry.io/for/javascript/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'python',
            title: 'Python',
            to: 'https://sentry.io/for/python/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'ruby',
            title: 'Ruby',
            to: 'https://sentry.io/for/ruby/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'node',
            title: 'Node',
            to: 'https://sentry.io/for/node/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'go',
            title: 'Go',
            to: 'https://sentry.io/for/go/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'dotnet',
            title: '.Net',
            to: 'https://sentry.io/for/dot-net/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'ios',
            title: 'ios',
            to: 'https://sentry.io/for/cocoa/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'android',
            title: 'android',
            to: 'https://sentry.io/for/android/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'seeall',
            title: 'See All',
            to: 'https://sentry.io/platforms/',
            variant: 'outline',
            withArrowBtn: true,
            type: 'a',
          },
        ],
      },
      {
        id: 'whySentry',
        title: 'Why Sentry?',
        children: [
          {
            id: 'web',
            title: 'Web',
            to: 'https://sentry.io/for/full-stack/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'mobile',
            title: 'Mobile',
            to: 'https://sentry.io/for/mobile/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'native',
            title: 'Native',
            to: 'https://sentry.io/for/native/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'gaming',
            title: 'Gaming',
            to: 'https://sentry.io/for/gaming/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'internetOfThings',
            title: 'Internet Of Things',
            to: 'https://sentry.io/for/iot/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'data',
            title: 'Data',
            to: 'https://sentry.io/for/data/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'enterprise',
            title: 'Enterprise',
            to: 'https://sentry.io/for/enterprise/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'openSource',
            title: 'Open Source',
            to: 'https://sentry.io/for/open-source/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'security',
            title: 'Security & Compliance',
            to: 'https://sentry.io/security/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'customers',
            title: 'Customers',
            to: 'https://sentry.io/customers/',
            variant: 'ghost',
            type: 'a',
          },
        ],
      },
      {
        id: 'features',
        title: 'Features',
        children: [
          {
            id: 'customQueries',
            title: 'Custom Queries',
            to: 'https://sentry.io/features/custom-queries/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'dashboards',
            title: 'Dashboards',
            to: 'https://sentry.io/features/dashboards/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'crossProjectIssues',
            title: 'Cross-Project Issues',
            to: 'https://sentry.io/features/cross-project-issues/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'distributedTracing',
            title: 'Distributed Tracing',
            to: 'https://sentry.io/features/distributed-tracing/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'stackTraces',
            title: 'Stack Traces',
            to: 'https://sentry.io/features/stacktrace/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'context',
            title: 'Context',
            to: 'https://sentry.io/features/context/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'breadcrumbs',
            title: 'Breadcrumbs',
            to: 'https://sentry.io/features/breadcrumbs/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'releases',
            title: 'Releases',
            to: 'https://sentry.io/features/releases/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'issueOwners',
            title: 'Issue Owners',
            to: 'https://sentry.io/features/owners/',
            variant: 'ghost',
            type: 'a',
          },
        ],
      },
    ],
  },
  {
    id: 'pricing',
    title: 'Pricing',
    type: 'a',
    to: 'https://sentry.io/pricing',
    variant: 'ghost',
    className: '',
  },
  {
    id: 'docs',
    title: 'Docs',
    type: 'a',
    to: 'https://docs.sentry.io',
    variant: 'ghost',
    className: '',
  },
  {
    id: 'blog',
    title: 'Blog',
    type: 'button',
    variant: 'ghost',
    className: '',
    children: [
      {
        id: 'blogMenu',
        title: '',
        children: [
          {
            id: 'sentryBlog',
            title: 'Sentry Blog',
            to: 'https://blog.sentry.io/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'enggBlog',
            title: 'Engineering Blog',
            to: 'https://sentry.engineering/',
            variant: 'ghost',
            type: 'a',
          },
          {
            id: 'changelog',
            title: 'Changelog',
            to: 'https://sentry.io/changelog/',
            variant: 'ghost',
            type: 'a',
          },
        ],
      },
    ],
  },
  {
    id: 'sandbox',
    title: 'Sandbox',
    type: 'a',
    to: 'https://try.sentry-demo.com/demo/start/',
    target: '_blank',
    variant: 'ghost',
    className: '',
  },
  {
    id: 'siginIn',
    title: 'Sign In',
    type: 'a',
    to: 'https://sentry.io/auth/login',
    variant: 'ghost',
    className: '',
  },
];
