name: Update Algolia index
on:
  push:
    branches:
      - master
jobs:
  index:
    name: Update Algolia index
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=6144'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@02f6c237bd2518259fed6c71566509edfb3f2b74 # v4

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4
        id: setup-node
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'includes/**'
              - 'platform-includes/**'
            dev-docs:
              - 'develop-docs/**'

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: nextjs-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            nextjs-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: '1.1.34'

      - run: pnpm install --frozen-lockfile

      # bun seems to be the most straightforward way to run a TypeScript script
      # without introducing another dependency like ts-node or tsx for everyone else

      - name: Build index for user docs
        run: pnpm enforce-redirects && pnpm generate-og-images && pnpm generate-doctree && pnpm next build && bun ./scripts/algolia.ts
        if: steps.filter.outputs.docs == 'true'
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          DOCS_INDEX_NAME: ${{ secrets.DOCS_INDEX_NAME }}
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
          NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }}
          SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0

      - name: Build index for developer docs
        run: git submodule init && git submodule update && pnpm enforce-redirects && pnpm generate-doctree && NEXT_PUBLIC_DEVELOPER_DOCS=1 pnpm next build && bun ./scripts/algolia.ts
        if: steps.filter.outputs.dev-docs == 'true'
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          DOCS_INDEX_NAME: ${{ secrets.DEVELOP_DOCS_INDEX_NAME }}
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
          NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }}
          SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_DEVELOPER_DOCS: 1
