name: 'Dependency Review'
on:
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Dependency Review
        uses: actions/dependency-review-action@e58c696e52cac8e62d61cc21fda89565d71505d7 # v4.3.1
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: high
