name: React to product-owners.yml changes
on:
  # This could be run manually, but the general expectation is that this fires
  # from GHA in getsentry/security-as-code on changes there.

  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    name: React to product-owners.yml changes
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: getsentry/action-setup-venv@5a80476d175edf56cb205b08bc58986fa99d1725 # v3.2.0
        with:
          python-version: 3.11.3

      - name: Get an auth token
        id: token
        uses: getsentry/action-github-app-token@97c9e23528286821f97fba885c1b1123284b29cc # v2.0.0
        with:
          app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - name: React to product-owners.yml changes
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: ./bin/react-to-product-owners-yml-changes.sh
