name: React to product-owners.yml changes
on:
  # This could be run manually, but the general expectation is that this fires
  # from GHA in getsentry/security-as-code on changes there.

  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    name: React to product-owners.yml changes
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: getsentry/action-setup-venv@5a80476d175edf56cb205b08bc58986fa99d1725 # v3.2.0
        with:
          python-version: 3.11.3

      - name: Get an auth token
        id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
          private-key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
          repositories: |
            security-as-code
            sentry-docs

      - name: React to product-owners.yml changes
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: ./bin/react-to-product-owners-yml-changes.sh
